# 第四章

In [8]:
data = np.random.randn(2,3)

In [33]:
data = [6,7,8,9,10]
arr1 = np.array(data)
data = [[[[6,7,8,9,10],[5,6,7,7,8]]]]
arr2 = np.array(data)
arr2
arr2.ndim

4

In [30]:
np.zeros([3,3])
np.ones([3,6])
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 每个数据都有dtype和shape属性
1. ndim表示数组的维度
2. 如果没有指明，数据默认是float64格式
3. 对切片的操作会反映在原数组上
4. 对多维数组进行切片的话，一次表示多个维度,:表示对整个轴上的索引，0表示行，1表示列
5. 布尔索引维度为一样，也可对多个布尔值进行&或者|
6. 神奇索引
7. 换轴transpose


In [38]:
print(arr1.dtype)
arr1.astype(np.float64)

int32


array([ 6.,  7.,  8.,  9., 10.])

In [44]:
np_string = np.array(["1.23","2.34"],dtype="S")
print(np_string.dtype)
np_string.astype(np.float).dtype

|S4


dtype('float64')

In [55]:
arr = np.arange(10)
arr[4:8]=12
arr1 = arr[3:8].copy()
arr1

array([ 3, 12, 12, 12, 12])

In [70]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[4,5,6],[6,7,8]]])
arr[0:1,1:2,1:3][0][0].tolist()
arr[:,:,0:1]=3
arr

array([[[3, 2, 3],
        [3, 5, 6],
        [3, 8, 9]],

       [[3, 3, 4],
        [3, 5, 6],
        [3, 7, 8]]])

In [72]:
np.array([[1,2,3]]).shape

(1, 3)

np.where(cond,x,y)
if True:
    x
else:
    y
zip(a,b) 将a，b两个列表打包成元组
cumsum() 累计求和，返回相同长度的数组
cumprod() 累计求积 从第一个元素开始
in1d(x,y)检查x中的元素是否在y中(为one而不是l)
np.savez("a.npz",a=arr,b=arr)

In [73]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
cond = np.array([True,False,True,True])
np.where(cond,x,y)

array([1, 6, 3, 4])

In [90]:
np.in1d([1,2,3],[ 1,  3, 4, 6,6,3,3,6 ,10])

array([ True, False,  True])

In [92]:
np.save("a.npy",x)
np.savez("b.npz",a=x,b=x)